valor = int(input('Digite um número para ver sua tabuada: '))

print('_'*15)
print('{} x 01 = {}'.format(valor, valor))
print('{} x 02 = {}'.format(valor, valor*2))
print('{} x 03 = {}'.format(valor, valor*3))
print('{} x 04 = {}'.format(valor, valor*4))
print('{} x 05 = {}'.format(valor, valor*5))
print('{} x 06 = {}'.format(valor, valor*6))
print('{} x 07 = {}'.format(valor, valor*7))
print('{} x 08 = {}'.format(valor, valor*8))
print('{} x 09 = {}'.format(valor, valor*9))
print('{} x 10 = {}'.format(valor, valor*10))
print('_'*15)