palavra = input('Digite algo: ')

print('O tipo primitivo desse valor é ', type(palavra))
print('Só tem espaços? ', palavra.isspace())
print('É um número?', palavra.isnumeric())
print('É alfabético?', palavra.isalpha())
print('É alfanúmerico?', palavra.isalnum())
print('Está em maiúsculo?', palavra.isupper())
print('Está em minúsculas?', palavra.islower())
print('Está capitalizada?', palavra.istitle())